version: "2"
services: 
  app:
    image: node:12
    container_name: node-prisma
    working_dir: /app
    command: "yarn dev"
    ports: 
      - 3333:3333
    tty: true
    volumes: 
      - ../:/app
  mariadb:
    image: mariadb:latest
    container_name: node-prisma-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: q1w2e3r4
      MYSQL_DATABASE: nodeprisma
      MYSQL_USER: root
      MYSQL_PASSWORD: q1w2e3r4
    ports: 
      - 3306:3306